# This workflow publishes the module to Maven and is triggered when a Draft release is published.

name: Publish Release

on:
  release:
    types: [released]

jobs:
  upload_to_maven_central:
    runs-on: ubuntu-latest

    steps:
#    - name: Assert branch name is master
#      if: ${{ github.ref != 'refs/heads/master' }}
#      run: |
#        echo "Releases can be performed only on master branch"
#        exit 1

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.COMMIT_ACCESS_TOKEN }}

    - name: get version from tag
      id: get_version
      run: |
        echo $GITHUB_REF
        releaseVersion="${GITHUB_REF/refs\/tags\//}"
        releaseVersion="${releaseVersion//v/}"
        echo $releaseVersion
        echo "::set-output name=VERSION::$releaseVersion"

    - name: Set up publishing to maven central
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

    - name: mvn versions
      run: mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}


#    - name: Publish
#      run: |
#        mvn --no-transfer-progress --batch-mode \
#          -Dgpg.passphrase='${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}' \
#          -DskipTests deploy -P release
#      env:
#        MAVEN_USERNAME: ${{ secrets.D11_NEXUS_USERNAME }}
#        MAVEN_PASSWORD: ${{ secrets.D11_NEXUS_PASSWORD }}
#        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
#
#    - name: Bump version
#      run: .ci/scripts/bump-version.sh
